apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: find-cnpj-api
  description: Serviço responsável por disponibilizar uma api para consulta de cnpj.
  tags:
    - java
    - quarkus
  links:
    - url: https://quarkus.io/
      title: Framework
      icon: dashboard
    - url: https://quarkus.io/guides/
      title: docs
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ruan
  system: find-cnpj-api
